### ISSUE TITLE
Path for starting tray applet

### ISSUE THREAD

**Issue by DerickEddington** [blitz/tuxedo-nixos#1]
The "Tray autostart" feature tries to run the command `/usr/bin/tuxedo-control-center --tray`, but that does not work in Nix because the executable does not exist at that path and is located elsewhere in the `/nix/store/`.

I encountered this issue with the MATE Desktop in NixOS 21.05, and I guess the same issue would occur with other desktop environments.  After running `tuxedo-control-center` for the first time, it defaults to enabling its "Tray autostart" feature, but the next time you login it fails to start.  I quick-fixed this by changing MATE's `System > Preferences > Personal > Startup Applications > TUXEDO Control Center` to use the command `tuxedo-control-center --tray`.  Would the proper fix be to patch the source code via the Nix package so that this uses the absolute `/nix/store/...` path of the executable instead?  I am not familiar with Electron and Node.js, and am only barely familiar with Nix, so I did not look into doing that.

**Comment by blitz** [comment]
I have resorted to patching the sources in these cases. See for example the patch for the `tccd` location [here](https://github.com/blitz/tuxedo-nixos/blob/master/nix/tuxedo-control-center/default.nix#L74):

```nix
  # TCC by default writes its config to /etc/tcc, which is
  # inconvenient. Change this to a more standard location.
  #
  # It also hardcodes binary path.
  postPatch = ''
    substituteInPlace src/common/classes/TccPaths.ts \
      --replace "/etc/tcc" "/var/lib/tcc" \
      --replace "/opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/service/tccd" "$out/bin/tccd"
   '';
```

I'd be glad if you can give patching this a shot. :) Otherwise, I'll get to it when I have a free evening in a week or so.

**Comment by DerickEddington** [comment]
I'll give it a try.

**Comment by blitz** [comment]
@DerickEddington I got some time after all. Sorry, if you already started. Can you give #3 a try?

**Comment by DerickEddington** [comment]
Cool. I'd not started.

I tried #3 and it works.  After a user runs `tuxedo-control-center` for the first time, the tray applet now auto-starts for subsequent logins, because it now uses the correct `/nix/store/...` path of the executable.

**Comment by blitz** [comment]
@DerickEddington Thanks for testing!
