### ISSUE TITLE
README.md hardware.tuxedo seems to be wrong

### ISSUE THREAD

**Issue by Qutn** [blitz/tuxedo-nixos#2]
Hi !

First of all, thank you for this project.
In the readme it is written "hardware.tuxedo.enable" however the module seems to define a "tuxedo-control-center" instead of "tuxedo", and while building by following the readme, it didn't work, changing "hardware.tuxedo.enable" to "hardware.tuxedo-control-center.enable" did the trick though

**Comment by blitz** [comment]
Thanks for reporting! Should be fixed now.
