### ISSUE TITLE
No Temp no Fan

### ISSUE THREAD

**Issue by Qutn** [blitz/tuxedo-nixos#4]
Hi,

On my stellaris 15 on a fresh install, the control center displays a 0 for the cpu temp, a 0 for the CPU fan and nothing for the gpu.

It is hard for me to know if this is strictly related to NixOS but it was working fine two days ago on a gentoo installation.

Here are the relevant parts of my .nix conf

```
{pkgs, config, lib, ...}:

let
  tuxedo = import (builtins.fetchTarball "https://github.com/blitz/tuxedo-nixos/archive/master.tar.gz");
in 

{
  
  boot.kernelPackages = pkgs.linuxPackages_zen;

  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.driSupport = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.tuxedo-keyboard.enable = true;

  imports = [ tuxedo.module ];

  hardware.tuxedo-control-center.enable = true;
   
}
```

And I also added this tuxedo-keyboard in boot.kernelModules but I'm unsure this has any effect.

Thank you for your work

**Comment by blitz** [comment]
Thanks for the report. Can you provide logs (dmesg / journalctl)? I'm pretty sure we're missing some dependencies for Nvidia GPUs. So far I've only used this on a laptop with Intel CPU and iGPU.

**Comment by Qutn** [comment]
Hi,

I'm sorry it took such a long time for me to answer, many things happened and I ended up doing a completely new install
and now it works perfectly.

The only line that I think has changed is 

boot.kernelPackages = pkgs.linuxPackages_zen;

which is now 

boot.kernelPackages = pkgs.linuxKernel.packages.linux_zen;

So I'm pretty sure that my config was just bad. I apologise for the issue but at least it fixed itself !
