### ISSUE TITLE
Build broken on nixos-unstable

### ISSUE THREAD

**Issue by Occhioverde** [blitz/tuxedo-nixos#5]
Good morning.

As per the title, today I installed NixOS on my new Tuxedo InfinityBook S15 and I tried to setup the Tuxedo Control Center using this flake, but the build failed with the `command failed sh -c -- node-gyp rebuild` error.

I read the Troubleshooting part in this repo's README, but just by looking at the build log I wasn't able to determine which workaround I should apply, so maybe someone with a bit more experience is able to point me in the right direction.

Since the output is quite verbose, you can find it in [this](https://privatebin.devol.it/?e1a2fd1c5526a4ed#FWEpJsChXPAheAJF8gDhMtKGLi29sYbWSSqrym8qQ4S4) paste, while my NixOS config is available [here](https://cloud.nexxontech.it/s/apYjeKR9WPxecQD).

Thank you very much in advance to anyone who can help me.

**Comment by blitz** [comment]
Looking at your config, you are overriding the nixpkgs that tuxedo-control-center builds against. So far only 22.05 works and is tested, but you are overriding it with unstable. If you drop this line:

```
    tuxedo-nixos = {
      url = "github:blitz/tuxedo-nixos";
      inputs.nixpkgs.follows = "nixpkgs"; # <<<<<
    };
```

It should work (with mixed nixpkgs...).

Now it would be very nice, if the derivation would actually build against unstable, but the whole Javascript/Electron packaging is a mess. :( I would like to switch to shipping the pre-built debian binaries, but that is still problematic, because they have hardcoded absolute paths... *sigh*

**Comment by Occhioverde** [comment]
Thank you very much for your reply!

I tried to remove the `inputs.nixpkgs.follows = "nixpkgs";` line, but the problem doesn't seem to be fixed:

```
root@Ricky-InfinityBook /e/nixos# nixos-rebuild boot
warning: updating lock file '/etc/nixos/flake.lock':
• Updated input 'tuxedo-nixos/nixpkgs':
    follows 'nixpkgs'
  → 'github:NixOS/nixpkgs/814f8f3363cecee7cce314286846e4da5e92d689' (2022-11-15)
building the system configuration...
error: builder for '/nix/store/1lm82kl4swcyp7si9kq0fnk7dw50vb2b-tuxedo-control-center-1.1.3.drv' failed with exit code 1;
       last 10 log lines:
       > npm ERR! gyp ERR! System Linux 6.0.7-zen1
       > npm ERR! gyp ERR! command "/nix/store/gl1p4kgknkb2bmcwnpdgppfhscmh0x0f-nodejs-18.12.1/bin/node" "/nix/store/gl1p4kgknkb2bmcwnpdgppfhscmh0x0f-nodejs-18.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       > npm ERR! gyp ERR! cwd /nix/store/rws2r39cwq4rc847bh60c6hjjdfwa4ny-tuxedo-control-center-1.1.3/lib/node_modules/tuxedo-control-center/node_modules/abstract-socket
       > npm ERR! gyp ERR! node -v v18.12.1
       > npm ERR! gyp ERR! node-gyp -v v9.1.0
       > npm ERR! gyp ERR! not ok
       > 
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /build/.npm/_logs/2022-11-17T14_23_41_916Z-debug-0.log
       > 
       For full logs, run 'nix log /nix/store/1lm82kl4swcyp7si9kq0fnk7dw50vb2b-tuxedo-control-center-1.1.3.drv'.
error: 1 dependencies of derivation '/nix/store/qy1vx9c7b4bwdd57hwj8ab7vnwsl1y4q-tuxedo-control-center-1.1.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ywyni05n750g3qdy7wla4zh76qsk97ns-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6y9bi02s81h0mhm8icjs7q7f3dgdcrwg-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i948jcdnllgypxv1x0nmg3i0bp2jb80q-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ixb5lpy34kh8vdxlabwgb68alfhf31nr-tuxedo-control-center-1.1.3_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s8dnkiq5gzyxjx09afkiqba9ggyqaad4-unit-tccd-sleep.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zpq028nqd2y1937mpzycl30km8lzd4wv-unit-tccd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2yzajkfg3qvjnvl3l4q0c8ir1hdv5r56-nixos-system-Ricky-InfinityBook-22.11.20221112.d8f2c4d.drv' failed to build
```

I verified that the commit to which the flake locked is indeed the latest one in the `nixos-22.05` branch, but the derivation path seems to be unchanged (`/nix/store/1lm82kl4swcyp7si9kq0fnk7dw50vb2b-tuxedo-control-center-1.1.3.drv`). Maybe some dependency has changed in stable too?

**Comment by blitz** [comment]
@Occhioverde Did you re-run `nix flake lock`? The derivation is actually built in CI and by me locally. It's really unlikely that it would fail to build for you.

**Comment by Occhioverde** [comment]
No, I didn't run `nix flake lock`, but as you can see in the first lines of the log, the flake locked on `github:NixOS/nixpkgs/814f8f3363cecee7cce314286846e4da5e92d689` (the latest commit available in the `nixos-22.05` branch when I wrote the reply).

Just to be sure, tho, I just deleted the `flake.lock` file, rebuilt the system without the `tuxedo-nixos` input, ran the garbage collector and then tried again to add TCC, but I got the same result:

```
root@Ricky-InfinityBook /e/nixos# nixos-rebuild switch
warning: updating lock file '/etc/nixos/flake.lock':
• Added input 'tuxedo-nixos':
    'github:blitz/tuxedo-nixos/12bb6c354f9a9b68e16a877ed674de88d6996e2c' (2022-10-16)
• Added input 'tuxedo-nixos/flake-compat':
    'github:edolstra/flake-compat/b4a34015c698c7793d592d66adbab377907a2be8' (2022-04-19)
• Added input 'tuxedo-nixos/nixpkgs':
    'github:NixOS/nixpkgs/8de8b98839d1f20089582cfe1a81207258fcc1f1' (2022-10-16)
building the system configuration...
error: builder for '/nix/store/1lm82kl4swcyp7si9kq0fnk7dw50vb2b-tuxedo-control-center-1.1.3.drv' failed with exit code 1;
       last 10 log lines:
       > npm ERR! gyp ERR! System Linux 6.0.7-zen1
       > npm ERR! gyp ERR! command "/nix/store/gl1p4kgknkb2bmcwnpdgppfhscmh0x0f-nodejs-18.12.1/bin/node" "/nix/store/gl1p4kgknkb2bmcwnpdgppfhscmh0x0f-nodejs-18.12.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
       > npm ERR! gyp ERR! cwd /nix/store/rws2r39cwq4rc847bh60c6hjjdfwa4ny-tuxedo-control-center-1.1.3/lib/node_modules/tuxedo-control-center/node_modules/abstract-socket
       > npm ERR! gyp ERR! node -v v18.12.1
       > npm ERR! gyp ERR! node-gyp -v v9.1.0
       > npm ERR! gyp ERR! not ok
       > 
       > npm ERR! A complete log of this run can be found in:
       > npm ERR!     /build/.npm/_logs/2022-11-20T14_15_49_679Z-debug-0.log
       > 
       For full logs, run 'nix log /nix/store/1lm82kl4swcyp7si9kq0fnk7dw50vb2b-tuxedo-control-center-1.1.3.drv'.
error: 1 dependencies of derivation '/nix/store/qy1vx9c7b4bwdd57hwj8ab7vnwsl1y4q-tuxedo-control-center-1.1.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ywyni05n750g3qdy7wla4zh76qsk97ns-dbus-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6y9bi02s81h0mhm8icjs7q7f3dgdcrwg-man-paths.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i948jcdnllgypxv1x0nmg3i0bp2jb80q-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/ixb5lpy34kh8vdxlabwgb68alfhf31nr-tuxedo-control-center-1.1.3_fish-completions.drv' failed to build
error: 1 dependencies of derivation '/nix/store/s8dnkiq5gzyxjx09afkiqba9ggyqaad4-unit-tccd-sleep.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/zpq028nqd2y1937mpzycl30km8lzd4wv-unit-tccd.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2yzajkfg3qvjnvl3l4q0c8ir1hdv5r56-nixos-system-Ricky-InfinityBook-22.11.20221112.d8f2c4d.drv' failed to build
```

Since the flake works for you, may I ask you to verify if your derivation hash is the same as mine?

**Comment by blitz** [comment]
> Since the flake works for you, may I ask you to verify if your derivation hash is the same as mine?

The CI says:

https://hercules-ci.com/accounts/github/blitz/derivations/%2Fnix%2Fstore%2F8cm030hh0gla0wd87m4266fzj0w2s4nc-tuxedo-control-center-1.1.3.drv?via-job=003c0f0b-3b27-4c45-b41a-b528f28050bb

The issue seems to be that the [module](https://github.com/blitz/tuxedo-nixos/blob/master/nix/module.nix) builds TCC with the current `pkgs`, which in your case is nixpkgs-unstable.

If you set `hardware.tuxedo-control-center.package` to the `packages.x86_64-linux.default` output of the flake you should be fine (albeit with a pretty large closure...).

**Comment by Occhioverde** [comment]
That did the trick! Thank you very much!

As a last question, out of curiosity, I noticed that you have a Nix binary cache at https://blitz.cachix.org/, but I don't understand if it gets updated with the new TCC versions' outputs. Should I add it to my system's substituters or would that be pointless?

**Comment by signaleleven** [comment]
I'm sorry, this is really more of a Nix question, but...

> If you set hardware.tuxedo-control-center.package to the packages.x86_64-linux.default output of the flake you should be fine (albeit with a pretty large closure...).

Can you elaborate on this? I am having the same issue (with 22.11, not unstable, but it's the same thing of course...)

Solved by looking at [your nixos-config](https://github.com/blitz/nix-configs/blob/7b516b0153fb3c5a10312e1ac255c1ab9ed9b4fc/flake.nix#L82), @blitz ! Thanks
